version: "3"

services:
  db:
    container_name: receipt_service_database
    image: postgres:latest
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - server-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"


  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    container_name: receipt_service_server
    volumes:
      - ./server:/server
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8003:8003"

  adminer:
    image: adminer:latest
    restart: always
    container_name: receipt_service_adminer
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8083:8080"


volumes:
  server-db-data:
