"""Receipt History

Revision ID: d74ff4b02fd6
Revises: 7456cfda13a7
Create Date: 2023-09-25 16:51:36.984715

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d74ff4b02fd6"
down_revision: Union[str, None] = "7456cfda13a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt_history",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Unique id"
        ),
        sa.Column("receipt_id", sa.Integer(), nullable=False, comment="Receipt id"),
        sa.Column("product_id", sa.Integer(), nullable=False, comment="Product id"),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total", sa.DECIMAL(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_receipt_history_price_btree",
        "receipt_history",
        ["price"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_receipt_history_quantity_btree",
        "receipt_history",
        ["quantity"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_receipt_history_total_btree",
        "receipt_history",
        ["total"],
        unique=False,
        postgresql_using="btree",
    )
    op.drop_index("ix_product_id_btree", table_name="product")
    op.drop_index("ix_receipt_id_btree", table_name="receipt")
    op.drop_index("ix_user_id_btree", table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_id_btree", "user", ["id"], unique=False)
    op.create_index("ix_receipt_id_btree", "receipt", ["id"], unique=False)
    op.create_index("ix_product_id_btree", "product", ["id"], unique=False)
    op.drop_index(
        "ix_receipt_history_total_btree",
        table_name="receipt_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_receipt_history_quantity_btree",
        table_name="receipt_history",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_receipt_history_price_btree",
        table_name="receipt_history",
        postgresql_using="btree",
    )
    op.drop_table("receipt_history")
    # ### end Alembic commands ###
